version: "3.8"

services:
  web:
    build: ./StationService
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./StationService/:/usr/src/StationService/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=station
      - POSTGRES_PASSWORD=station
      - POSTGRES_DB=station_dev

volumes:
  postgres_data: