version: "3.8"

services:
  web:
    build: ./StationService
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./StationService/:/usr/src/StationService/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=station
      - POSTGRES_PASSWORD=station
      - POSTGRES_DB=station_dev

volumes:
  postgres_data:
#     networks:
#       - nginx_network
#       - database1_network
#     depends_on:
#       - database1
#   #================================================================
#   nginx:
#     image: nginx:1.21.6 
#     ports:
#       - 8000:80
#     volumes:
#       - ./config/nginx/conf.d:/etc/nginx/conf.d
#       - static_volume:/opt/services/station/static 
#       - media_volume:/opt/services/station/media
#     depends_on:
#       - station
#     networks:
#       - nginx_network
#   #================================================================
#   database1:
#     image: postgres:14.2
#     env_file:
#       - config/db/database1_env  
#     networks:
#       - database1_network
#     volumes:
#       - database1_volumes:/var/lib/postgresql/data

# networks:
#   nginx_network:
#     driver: bridge
#   database1_network:
#     driver: bridge

# volumes:
#   database1_volumes:
#   static_volume:  
#   media_volume: