# Generated by Django 4.2 on 2024-01-28 05:07

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("idarticle", models.AutoField(primary_key=True, serialize=False)),
                ("codArticle", models.CharField(db_column="CodArticle", max_length=10)),
                ("nomArticle", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "articles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("idcli", models.AutoField(primary_key=True, serialize=False)),
                ("codcli", models.CharField(max_length=10, unique=True)),
                ("raisonsoc", models.CharField(max_length=255)),
                ("pays", django_countries.fields.CountryField(max_length=2)),
                ("ville", models.CharField(max_length=100)),
                ("adrgeo", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("telresp1", models.CharField(max_length=40)),
                ("telresp2", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "clients",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Ctrcaisse",
            fields=[
                ("idctrcaisse", models.AutoField(primary_key=True, serialize=False)),
                ("codcaisse", models.CharField(max_length=20)),
                ("typctr", models.IntegerField()),
            ],
            options={
                "db_table": "ctrcaisse",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cuve",
            fields=[
                ("idcuve", models.AutoField(primary_key=True, serialize=False)),
                ("codecuve", models.CharField(max_length=10, unique=True)),
                ("nomcuve", models.CharField(max_length=40)),
                ("capcuve", models.IntegerField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
            ],
            options={
                "db_table": "cuves",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FamilleArticle",
            fields=[
                ("idfamille", models.AutoField(primary_key=True, serialize=False)),
                ("codfamille", models.CharField(max_length=10, unique=True)),
                ("nomfamille", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "FamilleArticle",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                ("idfourn", models.AutoField(primary_key=True, serialize=False)),
                ("codfourn", models.CharField(max_length=10, unique=True)),
                ("raisonsoc", models.CharField(max_length=255)),
                ("pays", django_countries.fields.CountryField(max_length=2)),
                ("ville", models.CharField(max_length=100)),
                ("adrgeo", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("telresp1", models.CharField(max_length=40)),
                ("telresp2", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "fournisseurs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Journeescomptable",
            fields=[
                ("idjournee", models.AutoField(primary_key=True, serialize=False)),
                ("datecomptable", models.DateField()),
                ("joursts", models.IntegerField()),
                ("exocpta", models.IntegerField()),
            ],
            options={
                "db_table": "journeescomptables",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Lignebilan",
            fields=[
                ("idligbilan", models.AutoField(primary_key=True, serialize=False)),
                ("codlign", models.CharField(max_length=10)),
                ("libbilan", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "lignebilan",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Natoperation",
            fields=[
                ("idnatope", models.AutoField(primary_key=True, serialize=False)),
                ("codope", models.CharField(max_length=20)),
                ("libope", models.CharField(max_length=40)),
                ("saiqte", models.BooleanField()),
                ("saival", models.BooleanField()),
            ],
            options={
                "db_table": "natoperation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stationservice",
            fields=[
                ("idstation", models.AutoField(primary_key=True, serialize=False)),
                ("codstation", models.CharField(max_length=10, unique=True)),
                ("pays", django_countries.fields.CountryField(max_length=2)),
                ("ville", models.CharField(max_length=100)),
                ("adrgeo", models.CharField(max_length=255)),
                ("telresp1", models.CharField(max_length=40)),
                ("telresp2", models.CharField(max_length=40)),
                ("nbdecuve", models.IntegerField()),
                ("nbdepompe", models.IntegerField()),
                ("capcuve", models.IntegerField()),
                ("jourcpta", models.DateField()),
                ("exocpta", models.IntegerField()),
            ],
            options={
                "db_table": "stationservices",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("iduser", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("profiluser", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "utilisateurs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Vtesclientcredit",
            fields=[
                ("idvtecli", models.AutoField(primary_key=True, serialize=False)),
                ("datemvt", models.DateField()),
                ("quantite", models.IntegerField()),
                ("prixunitaire", models.IntegerField()),
                ("montant", models.IntegerField()),
                ("exocpta", models.IntegerField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
                (
                    "idcli",
                    models.ForeignKey(
                        db_column="idcli",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.client",
                    ),
                ),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "vtesclientcredit",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Userstation",
            fields=[
                ("iduserstation", models.AutoField(primary_key=True, serialize=False)),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
                (
                    "iduser",
                    models.ForeignKey(
                        db_column="iduser",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "userstation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tarifsgaz",
            fields=[
                ("idtarifgaz", models.AutoField(primary_key=True, serialize=False)),
                ("datedebut", models.DateField()),
                ("datefin", models.DateField()),
                ("tarifrchg", models.IntegerField()),
                ("tarifcsg", models.IntegerField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
            ],
            options={
                "db_table": "tarifsgaz",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tarifsfourn",
            fields=[
                ("idtarfourn", models.AutoField(primary_key=True, serialize=False)),
                ("datedebut", models.DateField()),
                ("datefin", models.DateField()),
                ("monttarif", models.FloatField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
                (
                    "idfourn",
                    models.ForeignKey(
                        db_column="idfourn",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.fournisseur",
                    ),
                ),
            ],
            options={
                "db_table": "tarifsfourn",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TarifsClient",
            fields=[
                ("idtarcli", models.AutoField(primary_key=True, serialize=False)),
                ("datedebut", models.DateField()),
                ("datefin", models.DateField()),
                ("monttarif", models.FloatField()),
                (
                    "clients",
                    models.ForeignKey(
                        db_column="idcli",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.client",
                    ),
                ),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
            ],
            options={
                "db_table": "tarifsclient",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tarif",
            fields=[
                ("idtarif", models.AutoField(primary_key=True, serialize=False)),
                ("datedebut", models.DateField()),
                ("datefin", models.DateField()),
                ("monttarif", models.FloatField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
            ],
            options={
                "db_table": "tarifs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stocklubacc",
            fields=[
                ("idstklub", models.AutoField(primary_key=True, serialize=False)),
                ("datemvt", models.DateField()),
                ("qtestktheojm1", models.IntegerField()),
                (
                    "field_valstktheojm1",
                    models.IntegerField(db_column=" valstktheojm1"),
                ),
                ("vteqtejm1", models.IntegerField()),
                ("vtevaljm1", models.IntegerField()),
                (
                    "field_qteentreejour",
                    models.IntegerField(db_column=" qteentreejour"),
                ),
                ("valentreejour", models.IntegerField()),
                ("prixunachat", models.IntegerField()),
                ("qtestkfinal", models.IntegerField()),
                ("valstkfinal", models.IntegerField()),
                ("qtevtetotal", models.IntegerField()),
                ("valvtetotal", models.IntegerField()),
                ("qtevtejour", models.IntegerField()),
                ("valvtejour", models.IntegerField()),
                ("prixunvte", models.IntegerField()),
                ("exocpta", models.IntegerField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "stocklubacc",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stockcarburant",
            fields=[
                ("idstck", models.AutoField(primary_key=True, serialize=False)),
                ("datemvt", models.DateField()),
                ("qtestktheojm1", models.IntegerField()),
                (
                    "field_valstktheojm1",
                    models.IntegerField(db_column=" valstktheojm1"),
                ),
                (
                    "field_qteentreejour",
                    models.IntegerField(db_column=" qteentreejour"),
                ),
                ("valentreejour", models.IntegerField()),
                ("totatestkcuve", models.IntegerField()),
                ("totvalstkcuve", models.IntegerField()),
                ("vteqtejour", models.IntegerField()),
                ("vtevaljour", models.IntegerField()),
                ("qtestktheojour", models.IntegerField()),
                ("valstktheojour", models.IntegerField()),
                ("qtestkreeljour", models.IntegerField()),
                ("valstkreeljour", models.IntegerField()),
                ("diffqtestk", models.IntegerField()),
                ("diffvalstk", models.IntegerField()),
                ("exocpta", models.IntegerField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
                (
                    "idcuve",
                    models.ForeignKey(
                        db_column="idcuve",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.cuve",
                    ),
                ),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "stockcarburant",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="stationservice",
            name="iduser",
            field=models.ForeignKey(
                db_column="iduser",
                on_delete=django.db.models.deletion.CASCADE,
                to="profilAdmin.utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="StatArticle",
            fields=[
                ("idstatart", models.AutoField(primary_key=True, serialize=False)),
                ("periode", models.IntegerField()),
                ("qteachat", models.IntegerField()),
                ("mntachat", models.IntegerField()),
                ("qtevente", models.IntegerField()),
                ("mntvente", models.IntegerField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
                (
                    "idfamille",
                    models.ForeignKey(
                        db_column="idfamille",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.famillearticle",
                    ),
                ),
            ],
            options={
                "db_table": "statArticles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Regclient",
            fields=[
                ("idregcli", models.AutoField(primary_key=True, serialize=False)),
                ("datemvt", models.DateField()),
                ("montant", models.IntegerField()),
                ("modreg", models.IntegerField()),
                ("numchq", models.CharField(max_length=20)),
                ("numtel", models.CharField(max_length=20)),
                ("exocpta", models.IntegerField()),
                (
                    "idcli",
                    models.ForeignKey(
                        db_column="idcli",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.client",
                    ),
                ),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "regclients",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Pompecuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idpompe", models.IntegerField()),
                ("codpompe", models.CharField(max_length=10, unique=True)),
                ("descrpompe", models.CharField(max_length=40)),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
                (
                    "idcuve",
                    models.ForeignKey(
                        db_column="idcuve",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.cuve",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "pompecuve",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Natopecaisse",
            fields=[
                ("idnatopecaisse", models.AutoField(primary_key=True, serialize=False)),
                (
                    "idctrcaisse",
                    models.ForeignKey(
                        db_column="idctrcaisse",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.ctrcaisse",
                    ),
                ),
                (
                    "idnatope",
                    models.ForeignKey(
                        db_column="idnatope",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.natoperation",
                    ),
                ),
            ],
            options={
                "db_table": "natopecaisse",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Mvtsodiverse",
            fields=[
                ("idmvtod", models.AutoField(primary_key=True, serialize=False)),
                ("datemvt", models.DateField()),
                ("numveh", models.CharField(max_length=30)),
                ("field_quantite", models.IntegerField(db_column="  quantite")),
                ("field_prixunitaire", models.IntegerField(db_column=" prixunitaire")),
                ("montant", models.IntegerField()),
                ("comment", models.CharField(max_length=255)),
                ("modpai", models.IntegerField()),
                ("exocpta", models.IntegerField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "mvtsodiverses",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Mvtsgaz",
            fields=[
                ("idmvtgaz", models.AutoField(primary_key=True, serialize=False)),
                ("datemvt", models.DateField()),
                ("qtestktheojm1", models.IntegerField()),
                (
                    "field_valstktheojm1",
                    models.IntegerField(db_column=" valstktheojm1"),
                ),
                (
                    "field_vteqterechgjm1",
                    models.IntegerField(db_column=" vteqterechgjm1"),
                ),
                ("vtevalrechgjm1", models.IntegerField()),
                ("vteqteconsgjm1", models.IntegerField()),
                ("vtevalconsgjm1", models.IntegerField()),
                (
                    "field_qteentreejour",
                    models.IntegerField(db_column=" qteentreejour"),
                ),
                ("valentreejour", models.IntegerField()),
                ("prixunachat", models.IntegerField()),
                ("qtevterechgjour", models.IntegerField()),
                ("valvterechgjour", models.IntegerField()),
                ("prixunvterechg", models.IntegerField()),
                ("qtestkfinal", models.IntegerField()),
                ("valstkfinal", models.IntegerField()),
                ("qtevteconsgjour", models.IntegerField()),
                ("valvteconsgjour", models.IntegerField()),
                ("prixunvteconsg", models.IntegerField()),
                ("exocpta", models.IntegerField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "mvtsgaz",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Mvtsclient",
            fields=[
                ("idmvtcli", models.AutoField(primary_key=True, serialize=False)),
                ("datemvt", models.DateField()),
                ("soldejm1", models.IntegerField()),
                ("mntcrjour", models.IntegerField()),
                ("mntregjour", models.IntegerField()),
                ("mntotalcr", models.IntegerField(db_column="Mntotalcr")),
                ("mntotalreg", models.IntegerField(db_column="Mntotalreg")),
                ("soldejour", models.IntegerField()),
                ("exocpta", models.IntegerField()),
                (
                    "idcli",
                    models.ForeignKey(
                        db_column="idcli",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.client",
                    ),
                ),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "mvtsclients",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Mvtscaisse",
            fields=[
                ("idmvtcaisse", models.AutoField(primary_key=True, serialize=False)),
                ("datemvt", models.DateField()),
                ("contrpart", models.CharField(max_length=10)),
                ("libope", models.CharField(max_length=40)),
                ("numpiece", models.CharField(max_length=20)),
                ("quantite", models.IntegerField()),
                ("prixuntaire", models.IntegerField()),
                ("mtdepense", models.IntegerField()),
                ("mtrecette", models.IntegerField()),
                ("comment", models.CharField(max_length=255)),
                ("exocpta", models.IntegerField()),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idnatope",
                    models.ForeignKey(
                        db_column="idnatope",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.natoperation",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "mvtscaisse",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Mvtpompecarburant",
            fields=[
                ("idmvtpompe", models.AutoField(primary_key=True, serialize=False)),
                ("idpompe", models.IntegerField()),
                ("datemvt", models.DateField()),
                ("indexfermeture", models.IntegerField()),
                ("indexouverture", models.IntegerField()),
                ("indexdiff", models.IntegerField()),
                ("remcuve", models.IntegerField()),
                ("vteqtejour", models.IntegerField()),
                ("prixdulitre", models.IntegerField()),
                ("recettejour", models.IntegerField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
                (
                    "idcuve",
                    models.ForeignKey(
                        db_column="idcuve",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.cuve",
                    ),
                ),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "mvtpompecarburant",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="journeescomptable",
            name="idstation",
            field=models.ForeignKey(
                db_column="idstation",
                on_delete=django.db.models.deletion.CASCADE,
                to="profilAdmin.stationservice",
            ),
        ),
        migrations.AddField(
            model_name="famillearticle",
            name="idnatoperation",
            field=models.ForeignKey(
                db_column="idnatoperation",
                on_delete=django.db.models.deletion.CASCADE,
                to="profilAdmin.natoperation",
            ),
        ),
        migrations.CreateModel(
            name="Entbllub",
            fields=[
                ("identbllub", models.AutoField(primary_key=True, serialize=False)),
                ("datemvt", models.DateField()),
                ("numbl", models.CharField(max_length=20)),
                ("qtelivree", models.IntegerField()),
                ("monlivre", models.IntegerField()),
                ("comment", models.CharField(max_length=255)),
                ("exocpta", models.IntegerField()),
                (
                    "idfourn",
                    models.ForeignKey(
                        db_column="idfourn",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.fournisseur",
                    ),
                ),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "entbllub",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Entblgaz",
            fields=[
                ("identblgaz", models.AutoField(primary_key=True, serialize=False)),
                ("datemvt", models.DateField()),
                ("numbl", models.CharField(max_length=20)),
                ("qtelivree", models.IntegerField()),
                ("monlivre", models.IntegerField()),
                ("comment", models.CharField(max_length=255)),
                ("exocpta", models.IntegerField()),
                (
                    "idfourn",
                    models.ForeignKey(
                        db_column="idfourn",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.fournisseur",
                    ),
                ),
                (
                    "idjournee",
                    models.ForeignKey(
                        db_column="idjournee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.journeescomptable",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "entblgaz",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Entblcarburant",
            fields=[
                ("identblcar", models.AutoField(primary_key=True, serialize=False)),
                ("idjournee", models.IntegerField()),
                ("datemvt", models.DateField()),
                ("numbl", models.CharField(max_length=20)),
                ("qtelivree", models.IntegerField()),
                ("monlivre", models.IntegerField()),
                ("prixachat", models.IntegerField()),
                ("idfourn", models.IntegerField()),
                ("comment", models.CharField(max_length=255)),
                ("exocpta", models.IntegerField()),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
            ],
            options={
                "db_table": "entblcarburant",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Detbllub",
            fields=[
                ("iddetbllub", models.AutoField(primary_key=True, serialize=False)),
                ("identbllub", models.IntegerField()),
                ("qtedetliv", models.IntegerField()),
                ("mondetliv", models.IntegerField()),
                ("remarkdet", models.CharField(max_length=255)),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
            ],
            options={
                "db_table": "detbllub",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Detblgaz",
            fields=[
                ("iddetblgaz", models.AutoField(primary_key=True, serialize=False)),
                ("identblgaz", models.IntegerField()),
                ("qtedetliv", models.IntegerField()),
                ("mondetliv", models.IntegerField()),
                ("remarkdet", models.CharField(max_length=255)),
                (
                    "idarticle",
                    models.ForeignKey(
                        db_column="idarticle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.article",
                    ),
                ),
            ],
            options={
                "db_table": "detblgaz",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Detblcarburant",
            fields=[
                ("iddetblcar", models.AutoField(primary_key=True, serialize=False)),
                ("identblcar", models.IntegerField()),
                ("qtedetliv", models.IntegerField()),
                ("mondetliv", models.IntegerField()),
                ("remarkdet", models.CharField(max_length=255)),
                (
                    "idcuve",
                    models.ForeignKey(
                        db_column="idcuve",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.cuve",
                    ),
                ),
            ],
            options={
                "db_table": "detblcarburant",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="cuve",
            name="idstation",
            field=models.ForeignKey(
                db_column="idstation",
                on_delete=django.db.models.deletion.CASCADE,
                to="profilAdmin.stationservice",
            ),
        ),
        migrations.CreateModel(
            name="Bilanjournalier",
            fields=[
                ("idbilan", models.AutoField(primary_key=True, serialize=False)),
                ("idjournee", models.IntegerField()),
                ("idligbilan", models.IntegerField()),
                ("datevalidation", models.DateField()),
                ("comment", models.CharField(db_column="Comment", max_length=255)),
                (
                    "idstation",
                    models.ForeignKey(
                        db_column="idstation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.stationservice",
                    ),
                ),
                (
                    "iduser",
                    models.ForeignKey(
                        db_column="iduser",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profilAdmin.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "bilanjournalier",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="article",
            name="idfamille",
            field=models.ForeignKey(
                db_column="idfamille",
                on_delete=django.db.models.deletion.CASCADE,
                to="profilAdmin.famillearticle",
            ),
        ),
    ]
