# Generated by Django 4.2 on 2024-02-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilAdmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pompecuve",
            name="descrpompe",
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name="stationservice",
            name="iduser",
        ),
        migrations.AddField(
            model_name="stationservice",
            name="iduser",
            field=models.ManyToManyField(to="profilAdmin.utilisateur"),
        ),
    ]
